name: Update Contributors List with Avatars

on:
  pull_request:
    types: [closed]  # 在 PR 合并时触发
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 午夜运行
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整 Git 历史以提取提交者
      - name: Scan Directories and Parse Usernames
        run: |
          echo "生成贡献者列表..."
          contributors=""
          # 扫描 SummerCamp 和 YuTuiMian 下的所有年份子目录
          for dir in SummerCamp/*/* YuTuiMian/*/*; do
            if [ -d "$dir" ] && [ -f "$dir/README.md" ]; then
              folder=$(basename "$dir")
              echo "处理文件夹: $dir"
              # 尝试从 README.md 获取 Contributor-Username
              username=$(grep -m 1 '^Contributor-Username:' "$dir/README.md" | sed 's/Contributor-Username: //')
              if [ -n "$username" ]; then
                echo "找到元数据用户名: $folder -> $username"
                contributors="$contributors$username,"
              else
                # 从 Git 提交历史获取提交者用户名
                git_username=$(git log --pretty="%an" "$dir/README.md" | head -n 1)
                if [ -n "$git_username" ]; then
                  # 尝试通过 GitHub API 获取 GitHub 用户名
                  github_username=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/search/users?q=$git_username in:name" | jq -r '.items[0].login // ""')
                  if [ -n "$github_username" ]; then
                    echo "找到 Git 用户名: $folder -> $github_username"
                    contributors="$contributors$github_username,"
                  else
                    echo "无 GitHub 用户名，使用文件夹名: $folder"
                    contributors="$contributors$folder,"
                  fi
                else
                  echo "无 Git 提交者信息，使用文件夹名: $folder"
                  contributors="$contributors$folder,"
                fi
              fi
            fi
          done
          # 清理贡献者列表，去除多余逗号并去重
          contributors=$(echo "$contributors" | tr ',' '\n' | grep -v '^$' | sort | uniq | tr '\n' ',' | sed 's/,$//')
          if [ -z "$contributors" ]; then
            echo "CONTRIBUTORS=" >> $GITHUB_ENV
          else
            echo "CONTRIBUTORS=$contributors" >> $GITHUB_ENV
          fi
          echo "最终贡献者列表: ${CONTRIBUTORS}"
      - name: Generate Contributors Table
        run: |
          echo "更新 README.md 贡献者表格..."
          table="| 头像 | 贡献者 |\n|------|--------|\n"
          if [ -n "${CONTRIBUTORS}" ]; then
            IFS=',' read -ra contrib_array <<< "${CONTRIBUTORS}"
            for contributor in "${contrib_array[@]}"; do
              table="$table| <img src=\"https://github.com/$contributor.png?size=40\" alt=\"$contributor\" width=\"40\" height=\"40\" onerror=\"this.src='https://github.com/avatars/u/0'\"> | $contributor |\n"
              echo "生成头像 URL: https://github.com/$contributor.png?size=40"
            done
          fi
          # 调试: 输出更新前 README.md 贡献者部分
          echo "更新前 README.md 贡献者部分:"
          grep -A 10 '<!-- ALL-CONTRIBUTORS-LIST:START -->' README.md || true
          # 将表格写入临时文件并验证
          echo -e "$table" > temp_table.md
          echo "生成表格内容:"
          cat temp_table.md
          # 替换 README.md 中的贡献者表格
          sed -i.bak '/<!-- ALL-CONTRIBUTORS-LIST:START -->/,/<!-- ALL-CONTRIBUTORS-LIST:END -->/c\<!-- ALL-CONTRIBUTORS-LIST:START -->\n'"$table"'\n<!-- ALL-CONTRIBUTORS-LIST:END -->' README.md
          # 调试: 输出更新后 README.md 贡献者部分（忽略退出码）
          echo "更新后 README.md 贡献者部分:"
          grep -A 10 '<!-- ALL-CONTRIBUTORS-LIST:START -->' README.md || true
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --staged --quiet || git commit -m 'docs: 更新贡献者列表（含头像）'
          echo "Git 状态:"
          git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: 更新贡献者列表（含头像）'
          title: '[自动] 更新贡献者列表'
          body: '基于 SummerCamp 和 YuTuiMian 下的所有年份目录自动更新贡献者列表（含头像）。'
          branch: auto-update-contributors
