name: Update Contributors List with Avatars

on:
  pull_request:
    types: [closed]  # 触发于 PR 合并
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次（可选，防止遗漏）
  workflow_dispatch:  # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.2
        with:
            readme_path: 'README.md'
            commit_msg: 'docs: update contributors list with avatars'
            contributor_template: '<tr><td><img src="https://github.com/%contributor%.png?size=40" alt="%contributor%" width="40" height="40"></td><td>%contributor%</td></tr>'  # 仅头像和用户名
            image_size: 40
            columns_per_row: 1
            output_path: './.all-contributorsrc'
            use_username: true
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ github.event.inputs.commit_msg || 'docs: update contributors list with avatars' }}
          title: '[Auto] Update Contributors List'
          body: 'Automated update of contributors list with avatars based on recent merges.'
          branch: auto-update-contributors