name: Update Contributors List with Avatars

on:
  pull_request:
    types: [closed]  # 在 PR 合并时触发
    branches-ignore:
      - 'auto-update-contributors-**' # 忽略自动创建的分支
  schedule:
    - cron: '0 0 * * 1'  # 每周一 UTC 午夜运行
  workflow_dispatch:  # 支持手动触发

permissions:
  contents: write  # 允许写仓库内容
  pull-requests: write  # 允许创建/更新 PR

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整 Git 历史以提取提交者
          token: ${{ secrets.PAT_TOKEN }}  # 使用 PAT 检出仓库
      - name: Set Branch Name
        run: |
          echo "BRANCH_NAME=auto-update-contributors-$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Scan Directories and Parse Usernames
        run: |
          echo "生成贡献者列表..."
          contributors=""
          # 扫描 SummerCamp 和 YuTuiMian 下的所有年份子目录
          for dir in SummerCamp/*/* YuTuiMian/*/*; do
            if [ -d "$dir" ] && [ -f "$dir/README.md" ]; then
              folder=$(basename "$dir")
              echo "处理文件夹: $dir"

              # 从 Git 提交历史获取最新提交的 SHA 和邮箱
              commit_info=$(git log -1 --pretty="%H %ae" "$dir/README.md")
              commit_sha=$(echo "$commit_info" | awk '{print $1}')
              git_email=$(echo "$commit_info" | awk '{print $2}')
              echo "最新提交 SHA: $commit_sha"
              echo "Git 提交者邮箱: $git_email"
              if [ -n "$commit_sha" ] && [ -n "$git_email" ]; then
                # 通过 GitHub API 获取提交者的 GitHub 用户名
                github_username=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  "https://api.github.com/repos/${{ github.repository }}/commits/$commit_sha" | jq -r '.author.login // ""')
                echo "API 查询结果: $github_username"
              
              # 从 Git 提交历史获取提交者用户名
              # git_username=$(git log --pretty="%an" "$dir/README.md" | head -n 1)
              # if [ -n "$git_username" ]; then
              #  # 尝试通过 GitHub API 获取 GitHub 用户名
              #  github_username=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
              #    "https://api.github.com/search/users?q=$git_username in:name" | jq -r '.items[0].login // ""')
                  
                if [ -n "$github_username" ]; then
                  echo "找到 Git 用户名: $folder -> $github_username"
                  contributors="$contributors$github_username,"
                else
                  echo "无 GitHub 用户名，跳过文件夹: $folder"
                fi
              else
                echo "无 Git 提交者信息，跳过文件夹: $folder"
              fi
            fi
          done
          # 清理贡献者列表，去除多余逗号并去重
          contributors=$(echo "$contributors" | tr ',' '\n' | grep -v '^$' | sort | uniq | tr '\n' ',' | sed 's/,$//')
          if [ -z "$contributors" ]; then
            echo "CONTRIBUTORS=" >> $GITHUB_ENV
          else
            echo "CONTRIBUTORS=$contributors" >> $GITHUB_ENV
          fi
          echo "最终贡献者列表: ${contributors}"
      - name: Generate Contributors Table
        run: |
          echo "更新 README.md 贡献者表格..."
          table='<div style="display: flex; flex-wrap: wrap;">'
          if [ -n "${CONTRIBUTORS}" ]; then
            IFS=',' read -ra contrib_array <<< "${CONTRIBUTORS}"
            for contributor in "${contrib_array[@]}"; do
              table="$table <a href=\"https://github.com/$contributor\"><img src=\"https://github.com/$contributor.png?size=40\" alt=\"$contributor\" title=\"$contributor\" width=\"40\" height=\"40\" style=\"margin: 5px;\" onerror=\"this.src='https://github.com/avatars/u/0'\"></a>"
              echo "生成头像 URL: https://github.com/$contributor.png?size=40"
            done
          fi
          table="$table</div>"
          # 将表格写入临时文件并验证
          echo -e "$table" > temp_table.md
          echo "生成表格内容:"
          cat temp_table.md
          # 替换 README.md 中的贡献者表格
          sed -i.bak '/<!-- ALL-CONTRIBUTORS-LIST:START -->/,/<!-- ALL-CONTRIBUTORS-LIST:END -->/c\<!-- ALL-CONTRIBUTORS-LIST:START -->\n'"$table"'\n<!-- ALL-CONTRIBUTORS-LIST:END -->' README.md
          echo "更新后 README.md 贡献者部分:"
          grep -A 10 '<!-- ALL-CONTRIBUTORS-LIST:START -->' README.md || true
          rm temp_table.md
          rm README.md.bak
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --staged --quiet || git commit -m 'docs: 更新贡献者列表（仅头像）'
          echo "Git 状态:"
          git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}  # 使用 PAT 创建 PR
          commit-message: 'docs: 更新贡献者列表（仅头像）'
          title: '[自动] 更新贡献者列表 - ${{ env.BRANCH_NAME }}'
          body: '基于 SummerCamp 和 YuTuiMian 下的所有年份目录自动更新贡献者列表（仅显示头像，链接到 GitHub 主页）。'
          branch: ${{ env.BRANCH_NAME }}
          base: main # 明确指定 PR 的目标分支
