name: Update Contributors List with Avatars

on:
  pull_request:
    types: [closed]  # Trigger on PR merge
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan Directories for Contributors
        run: |
          echo "Generating contributors from directories..."
          # Scan SummerCamp and YuTuiMian directories for folder names
          contributors=$(find SummerCamp YuTuiMian -maxdepth 1 -type d | grep -vE '^(SummerCamp|YuTuiMian)$' | sed 's|.*/||' | sort)
          echo "CONTRIBUTORS=$contributors" >> $GITHUB_ENV
      - name: Generate Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.2
        with:
          readme_path: 'README.md'
          commit_msg: 'docs: update contributors list with avatars'
          contributor_template: '<tr><td><img src="https://github.com/{{contributor}}.png?size=40" alt="{{contributor}}" width="40" height="40" onerror="this.src=''https://github.com/identicons/anonymous.png''"></td><td>{{contributor}}</td></tr>'
          image_size: 40
          use_username: false  # Use folder names instead of Git usernames
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTRIBUTORS: ${{ env.CONTRIBUTORS }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: update contributors list with avatars'
          title: '[Auto] Update Contributors List'
          body: 'Automated update of contributors list with avatars based on SummerCamp and YuTuiMian directories.'
          branch: auto-update-contributors
