name: Update Contributors List with Avatars

on:
  pull_request:
    types: [closed]  # 在 PR 合并时触发
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 午夜运行
  workflow_dispatch:  # 支持手动触发

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan Directories for Contributors
        run: |
          echo "生成贡献者列表..."
          # 扫描 SummerCamp 和 YuTuiMian 下的所有年份子目录中的贡献者文件夹
          contributors=$(find SummerCamp/*/ YuTuiMian/*/ -maxdepth 1 -type d | grep -vE '^(SummerCamp/[^/]+|YuTuiMian/[^/]+)$' | sed 's|.*/||' | sort | uniq)
          # 如果没有找到贡献者，设置为空字符串
          if [ -z "$contributors" ]; then
            echo "CONTRIBUTORS=" >> $GITHUB_ENV
          else
            # 转换为逗号分隔，去除多余换行和逗号
            echo "CONTRIBUTORS=$(echo "$contributors" | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_ENV
          fi
          # 调试：输出贡献者列表
          echo "Found contributors: ${CONTRIBUTORS}"
      - name: Generate Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.2
        with:
          readme_path: 'README.md'
          commit_msg: 'docs: 更新贡献者列表（含头像）'
          contributor_template: |-
            <tr><td><img src="https://github.com/{{contributor}}.png?size=40" alt="{{contributor}}" width="40" height="40" onerror="this.src='https://github.com/identicons/anonymous.png'"></td><td>{{contributor}}</td></tr>
          image_size: 40
          use_username: false  # 使用文件夹名而非 Git 用户名
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONTRIBUTORS: ${{ env.CONTRIBUTORS }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'docs: 更新贡献者列表（含头像）'
          title: '[自动] 更新贡献者列表'
          body: '基于 SummerCamp 和 YuTuiMian 下的所有年份目录自动更新贡献者列表（含头像）。'
          branch: auto-update-contributors
